# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_UCL.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1950, 1050)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(230, 97, 0);\n"
"    border-image: url(\"UCL.jpg\") 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(420, 890, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("background-color: rgb(26, 95, 180);\n"
"")
        self.add_button.setObjectName("add_button")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(630, 70, 601, 121))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.title.setObjectName("title")
        self.mute_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.mute_radio_button.setGeometry(QtCore.QRect(40, 850, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.mute_radio_button.setFont(font)
        self.mute_radio_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.mute_radio_button.setObjectName("mute_radio_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(1150, 890, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("background-color: rgb(26, 95, 180);\n"
"")
        self.delete_button.setObjectName("delete_button")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(790, 890, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.update_button.setFont(font)
        self.update_button.setStyleSheet("background-color: rgb(26, 95, 180);\n"
"")
        self.update_button.setObjectName("update_button")
        self.winner_line_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.winner_line_Edit.setGeometry(QtCore.QRect(390, 810, 201, 41))
        self.winner_line_Edit.setObjectName("winner_line_Edit")
        self.top_assistman_line_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.top_assistman_line_Edit.setGeometry(QtCore.QRect(980, 810, 201, 41))
        self.top_assistman_line_Edit.setObjectName("top_assistman_line_Edit")
        self.top_scorrer_line_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.top_scorrer_line_Edit.setGeometry(QtCore.QRect(680, 810, 201, 41))
        self.top_scorrer_line_Edit.setObjectName("top_scorrer_line_Edit")
        self.bes_manager_line_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.bes_manager_line_Edit.setGeometry(QtCore.QRect(1260, 810, 201, 41))
        self.bes_manager_line_Edit.setObjectName("bes_manager_line_Edit")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(60, 80, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("background-color: rgb(26, 95, 180);\n"
"")
        self.back_button.setObjectName("back_button")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(390, 220, 1081, 561))
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1950, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_button.setText(_translate("MainWindow", "add"))
        self.title.setText(_translate("MainWindow", "Champions League statistics of 21-st century"))
        self.mute_radio_button.setText(_translate("MainWindow", "mute"))
        self.delete_button.setText(_translate("MainWindow", "delete"))
        self.update_button.setText(_translate("MainWindow", "update"))
        self.winner_line_Edit.setPlaceholderText(_translate("MainWindow", "winner:"))
        self.top_assistman_line_Edit.setPlaceholderText(_translate("MainWindow", "top assistman:"))
        self.top_scorrer_line_Edit.setPlaceholderText(_translate("MainWindow", "top goalscorer:"))
        self.bes_manager_line_Edit.setPlaceholderText(_translate("MainWindow", "best manager:"))
        self.back_button.setText(_translate("MainWindow", "back"))
