# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1950, 1050)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(230, 97, 0);\n"
"    border-image: url(\"stadium.jpg\") 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(760, 760, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("background-color: rgb(26, 95, 180);")
        self.exit_button.setObjectName("exit_button")
        self.world_cup_button = QtWidgets.QPushButton(self.centralwidget)
        self.world_cup_button.setGeometry(QtCore.QRect(1100, 590, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.world_cup_button.setFont(font)
        self.world_cup_button.setStyleSheet("background-color: rgb(26, 95, 180);")
        self.world_cup_button.setObjectName("world_cup_button")
        self.UCL_button = QtWidgets.QPushButton(self.centralwidget)
        self.UCL_button.setGeometry(QtCore.QRect(460, 590, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UCL_button.setFont(font)
        self.UCL_button.setStyleSheet("background-color: rgb(26, 95, 180);\n"
"")
        self.UCL_button.setObjectName("UCL_button")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(560, 220, 881, 121))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.title.setObjectName("title")
        self.mute_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.mute_radio_button.setGeometry(QtCore.QRect(40, 850, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.mute_radio_button.setFont(font)
        self.mute_radio_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.mute_radio_button.setObjectName("mute_radio_button")
        self.music_dropbox = QtWidgets.QComboBox(self.centralwidget)
        self.music_dropbox.setGeometry(QtCore.QRect(1720, 60, 161, 41))
        self.music_dropbox.setPlaceholderText("")
        self.music_dropbox.setObjectName("music_dropbox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1950, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.world_cup_button.setText(_translate("MainWindow", "world cup"))
        self.UCL_button.setText(_translate("MainWindow", "Champions League"))
        self.title.setText(_translate("MainWindow", "Champions League and World Cup statistics of 21-st century"))
        self.mute_radio_button.setText(_translate("MainWindow", "mute"))
